-- Seed sample tours
INSERT INTO tours (title, slug, description, short_description, destination, category, price, original_price, duration, group_size, cover_image, highlights, inclusions, exclusions, is_featured, rating, review_count, itinerary)
VALUES
(
  'Magical Bali Retreat',
  'magical-bali-retreat',
  'Immerse yourself in the enchanting beauty of Bali with our carefully curated 7-day retreat. From the terraced rice paddies of Ubud to the pristine beaches of Nusa Dua, experience the best of this Indonesian paradise. Enjoy traditional Balinese spa treatments, explore ancient temples, and witness breathtaking sunsets over the Indian Ocean.',
  'Experience the enchanting beauty of Bali with temple visits, rice terraces, and pristine beaches.',
  'Bali, Indonesia',
  'beach',
  1299.00,
  1599.00,
  '7 Days / 6 Nights',
  '2-15 People',
  'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80',
  ARRAY['Visit iconic Tanah Lot Temple', 'Explore Ubud rice terraces', 'Traditional Balinese spa day', 'Sunset dinner at Jimbaran Bay', 'Snorkeling at Nusa Penida'],
  ARRAY['Return flights', 'Airport transfers', '4-star hotel accommodation', 'Daily breakfast', 'Guided tours', 'Travel insurance'],
  ARRAY['Personal expenses', 'Optional activities', 'Lunch and dinner (unless specified)', 'Visa fees'],
  true,
  4.8,
  124,
  '[{"day": 1, "title": "Arrival & Welcome", "description": "Airport pickup, hotel check-in, welcome dinner with traditional dance performance."}, {"day": 2, "title": "Ubud Exploration", "description": "Visit the Sacred Monkey Forest, Tegallalang Rice Terraces, and local art markets."}, {"day": 3, "title": "Temple Trail", "description": "Explore Tirta Empul water temple and Tanah Lot sunset temple visit."}, {"day": 4, "title": "Beach & Spa Day", "description": "Morning at Nusa Dua beach, afternoon traditional Balinese spa treatment."}, {"day": 5, "title": "Nusa Penida Day Trip", "description": "Boat trip to Nusa Penida for snorkeling and visiting Kelingking Beach."}, {"day": 6, "title": "Cultural Immersion", "description": "Balinese cooking class, visit Tirta Gangga water palace, sunset at Uluwatu."}, {"day": 7, "title": "Departure", "description": "Leisure morning, last-minute shopping, airport transfer."}]'::jsonb
),
(
  'Serengeti Safari Adventure',
  'serengeti-safari-adventure',
  'Embark on the ultimate African safari across the vast Serengeti plains. Witness the Great Migration, encounter the Big Five in their natural habitat, and experience the raw beauty of Tanzania. Stay in luxury tented camps under star-filled African skies and create memories that will last a lifetime.',
  'Witness the Great Migration and the Big Five on this unforgettable Tanzania safari.',
  'Tanzania, Africa',
  'adventure',
  2499.00,
  2999.00,
  '10 Days / 9 Nights',
  '4-12 People',
  'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80',
  ARRAY['Witness the Great Migration', 'Big Five game drives', 'Luxury tented camp experience', 'Ngorongoro Crater visit', 'Maasai village cultural tour'],
  ARRAY['Return flights', 'All park fees', 'Luxury tented camp stays', 'All meals during safari', 'Professional safari guide', '4x4 safari vehicle', 'Travel insurance'],
  ARRAY['Visa fees', 'Vaccinations', 'Personal expenses', 'Tips for guides', 'Travel to departure city'],
  true,
  4.9,
  89,
  '[{"day": 1, "title": "Arrival in Arusha", "description": "Welcome at Kilimanjaro Airport, transfer to Arusha hotel, safari briefing."}, {"day": 2, "title": "Tarangire National Park", "description": "Morning drive to Tarangire, afternoon game drive spotting elephants and baobab trees."}, {"day": 3, "title": "Ngorongoro Crater", "description": "Descend into the worlds largest volcanic caldera for a full day game drive."}, {"day": 4, "title": "Serengeti South", "description": "Drive to southern Serengeti, afternoon game drive, sunset at camp."}, {"day": 5, "title": "Central Serengeti", "description": "Full day game drive in the Seronera area, famous for big cat sightings."}, {"day": 6, "title": "Northern Serengeti", "description": "Drive north following the migration, visit the Mara River crossings."}, {"day": 7, "title": "Migration Day", "description": "Full day dedicated to witnessing the Great Migration spectacle."}, {"day": 8, "title": "Maasai Cultural Tour", "description": "Morning game drive, afternoon Maasai village visit and cultural exchange."}, {"day": 9, "title": "Final Safari", "description": "Dawn game drive for last wildlife sightings, transfer begins."}, {"day": 10, "title": "Departure", "description": "Morning transfer to Kilimanjaro Airport for departure."}]'::jsonb
),
(
  'Enchanting Paris Getaway',
  'enchanting-paris-getaway',
  'Fall in love with the City of Light on this romantic 5-day Parisian escape. Stroll along the Champs-Elysees, marvel at the Eiffel Tower at night, explore world-class museums, and indulge in exquisite French cuisine. From Montmartre to the Seine, every corner of Paris tells a story.',
  'A romantic escape through the City of Light with iconic landmarks and French cuisine.',
  'Paris, France',
  'cultural',
  1799.00,
  NULL,
  '5 Days / 4 Nights',
  '2-20 People',
  'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80',
  ARRAY['Eiffel Tower summit visit', 'Louvre Museum guided tour', 'Seine River dinner cruise', 'Montmartre walking tour', 'Versailles day trip'],
  ARRAY['Return flights', 'Boutique hotel accommodation', 'Daily breakfast', 'Airport transfers', 'Guided tours', 'Seine cruise ticket', 'Museum passes'],
  ARRAY['Lunch and dinner (unless specified)', 'Personal shopping', 'Optional activities', 'Travel insurance'],
  true,
  4.7,
  156,
  '[{"day": 1, "title": "Bonjour Paris!", "description": "Airport pickup, hotel check-in in Le Marais, evening walk along the Seine."}, {"day": 2, "title": "Iconic Paris", "description": "Morning at the Eiffel Tower, afternoon Louvre Museum tour, evening Champs-Elysees."}, {"day": 3, "title": "Art & Culture", "description": "Montmartre walking tour, Sacre-Coeur, afternoon at Musee dOrsay."}, {"day": 4, "title": "Versailles & Seine", "description": "Full day trip to Palace of Versailles, evening Seine River dinner cruise."}, {"day": 5, "title": "Au Revoir", "description": "Morning at leisure for shopping or cafe-hopping, airport transfer."}]'::jsonb
),
(
  'Maldives Paradise Escape',
  'maldives-paradise-escape',
  'Escape to the crystal-clear waters and white sandy beaches of the Maldives. This luxury island getaway features overwater villas, world-class diving, and ultimate relaxation. Watch dolphins at sunrise, snorkel with manta rays, and enjoy spa treatments overlooking the Indian Ocean.',
  'Luxury overwater villas, crystal waters, and world-class diving in paradise.',
  'Maldives',
  'beach',
  3299.00,
  3799.00,
  '6 Days / 5 Nights',
  '2-8 People',
  'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80',
  ARRAY['Overwater villa experience', 'Sunset dolphin cruise', 'Manta ray snorkeling', 'Couples spa treatment', 'Private sandbank picnic'],
  ARRAY['Return flights', 'Speedboat transfers', 'Overwater villa', 'All-inclusive meals', 'Snorkeling equipment', 'Dolphin cruise', 'Travel insurance'],
  ARRAY['Premium drinks', 'Scuba diving courses', 'Personal expenses', 'Spa treatments (beyond included)'],
  true,
  4.9,
  67,
  '[{"day": 1, "title": "Welcome to Paradise", "description": "Seaplane transfer to resort, overwater villa check-in, sunset cocktails."}, {"day": 2, "title": "Ocean Adventures", "description": "Morning snorkeling at house reef, afternoon sunset dolphin cruise."}, {"day": 3, "title": "Manta Ray Excursion", "description": "Boat trip to manta ray point, snorkeling with gentle giants, beach BBQ."}, {"day": 4, "title": "Spa & Relaxation", "description": "Morning overwater spa treatment, afternoon at leisure, stargazing dinner."}, {"day": 5, "title": "Sandbank Picnic", "description": "Private sandbank excursion with gourmet picnic, water sports afternoon."}, {"day": 6, "title": "Farewell", "description": "Sunrise yoga, final swim, speedboat transfer and departure."}]'::jsonb
),
(
  'Dubai Extravaganza',
  'dubai-extravaganza',
  'Experience the dazzling city of Dubai where modern marvels meet ancient traditions. From the towering Burj Khalifa to the golden dunes of the Arabian desert, this tour offers a perfect blend of luxury, adventure, and cultural discovery. Shop at the worlds largest mall, dine in the sky, and ride camels into the sunset.',
  'A dazzling blend of modern marvels, desert adventures, and Arabian luxury.',
  'Dubai, UAE',
  'luxury',
  1999.00,
  2399.00,
  '6 Days / 5 Nights',
  '2-20 People',
  'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80',
  ARRAY['Burj Khalifa At The Top visit', 'Desert safari with BBQ dinner', 'Dubai Marina yacht cruise', 'Abu Dhabi day trip', 'Gold & Spice Souk tour'],
  ARRAY['Return flights', '5-star hotel', 'Daily breakfast', 'Airport transfers', 'Desert safari', 'Burj Khalifa ticket', 'Dubai city tour'],
  ARRAY['Lunch and dinner (unless specified)', 'Shopping expenses', 'Optional activities', 'Travel insurance'],
  false,
  4.6,
  198,
  '[{"day": 1, "title": "Welcome to Dubai", "description": "Airport pickup, hotel check-in, evening Dubai Fountain show."}, {"day": 2, "title": "Modern Dubai", "description": "Burj Khalifa visit, Dubai Mall, afternoon at Dubai Marina."}, {"day": 3, "title": "Desert Adventure", "description": "Morning at leisure, afternoon desert safari with dune bashing and BBQ dinner."}, {"day": 4, "title": "Old Dubai & Culture", "description": "Gold Souk, Spice Souk, Dubai Creek abra ride, visit Dubai Museum."}, {"day": 5, "title": "Abu Dhabi Day Trip", "description": "Visit Sheikh Zayed Grand Mosque, Louvre Abu Dhabi, Corniche."}, {"day": 6, "title": "Departure", "description": "Morning yacht cruise at Dubai Marina, airport transfer."}]'::jsonb
),
(
  'Swiss Alps Explorer',
  'swiss-alps-explorer',
  'Discover the breathtaking beauty of the Swiss Alps with scenic train rides, charming villages, and snow-capped peaks. Ride the famous Glacier Express, explore Interlaken and Zermatt, and take in panoramic views of the Matterhorn. This tour is perfect for nature lovers and adventure seekers.',
  'Scenic train rides, charming villages, and panoramic views of the Matterhorn.',
  'Switzerland',
  'adventure',
  2799.00,
  NULL,
  '8 Days / 7 Nights',
  '4-16 People',
  'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=800&q=80',
  ARRAY['Glacier Express scenic train', 'Matterhorn panoramic views', 'Interlaken adventure sports', 'Lake Geneva cruise', 'Swiss chocolate factory tour'],
  ARRAY['Return flights', 'Swiss Travel Pass', 'Hotel accommodation', 'Daily breakfast', 'Glacier Express tickets', 'Guided mountain hikes', 'Travel insurance'],
  ARRAY['Lunch and dinner', 'Adventure sport activities (optional)', 'Personal expenses', 'Cable car upgrades'],
  false,
  4.8,
  73,
  '[{"day": 1, "title": "Arrival in Zurich", "description": "Airport pickup, transfer to Lucerne, lakeside welcome dinner."}, {"day": 2, "title": "Lucerne & Mt. Pilatus", "description": "Explore Lucerne old town, afternoon cable car to Mt. Pilatus summit."}, {"day": 3, "title": "Interlaken", "description": "Train to Interlaken, afternoon paragliding or lake cruise options."}, {"day": 4, "title": "Jungfraujoch", "description": "Train to Top of Europe at Jungfraujoch, stunning Alpine panoramas."}, {"day": 5, "title": "Glacier Express", "description": "Board the famous Glacier Express for a scenic journey to Zermatt."}, {"day": 6, "title": "Zermatt & Matterhorn", "description": "Gornergrat railway for Matterhorn views, afternoon village exploration."}, {"day": 7, "title": "Lake Geneva", "description": "Train to Montreux, Lake Geneva cruise, visit Chillon Castle, evening in Geneva."}, {"day": 8, "title": "Departure", "description": "Swiss chocolate factory visit, Geneva airport transfer."}]'::jsonb
);

-- Seed testimonials
INSERT INTO testimonials (name, location, avatar, rating, comment, tour_id, is_featured)
VALUES
(
  'Sarah Mitchell',
  'London, UK',
  'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80',
  5,
  'The Bali retreat was absolutely magical! Every detail was perfectly planned, from the temple visits to the beach sunsets. The team went above and beyond to make our honeymoon unforgettable. Cannot recommend MUS!C Travels enough!',
  (SELECT id FROM tours WHERE slug = 'magical-bali-retreat'),
  true
),
(
  'James & Linda Torres',
  'New York, USA',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
  5,
  'Our Serengeti safari was a once-in-a-lifetime experience. Seeing the wildebeest migration up close was incredible. The guides were knowledgeable and passionate, and the tented camps were surprisingly luxurious.',
  (SELECT id FROM tours WHERE slug = 'serengeti-safari-adventure'),
  true
),
(
  'Amara Okafor',
  'Lagos, Nigeria',
  'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=100&q=80',
  5,
  'Paris was everything I dreamed of and more. The guided Louvre tour was a highlight, and the Seine dinner cruise was pure romance. MUS!C Travels made everything seamless from start to finish.',
  (SELECT id FROM tours WHERE slug = 'enchanting-paris-getaway'),
  true
),
(
  'Raj Patel',
  'Mumbai, India',
  'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&q=80',
  5,
  'The Maldives trip exceeded all our expectations. The overwater villa was a dream, and swimming with manta rays was surreal. Worth every penny for this level of luxury and service.',
  (SELECT id FROM tours WHERE slug = 'maldives-paradise-escape'),
  true
),
(
  'Emily Zhang',
  'Sydney, Australia',
  'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80',
  4,
  'Dubai was a fantastic blend of modern luxury and traditional culture. The desert safari was the highlight of our trip. Great value for money and excellent organization throughout.',
  (SELECT id FROM tours WHERE slug = 'dubai-extravaganza'),
  false
),
(
  'Michael Brennan',
  'Dublin, Ireland',
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80',
  5,
  'The Swiss Alps tour was breathtaking in every sense. The Glacier Express ride alone was worth the trip. The hotels were charming and the scenery was jaw-dropping. Already planning our next trip with MUS!C Travels!',
  (SELECT id FROM tours WHERE slug = 'swiss-alps-explorer'),
  false
);
